### ISSUE TITLE
[TRACKER] Terrain Tools Menu UI

### ISSUE THREAD

**Issue by TokisanGames** [TokisanGames/Terrain3D#81]
Now that the bakers are added to the Tools menu, we can track other tool issues here. Future tools include:

- [ ]  Import/export

- [ ] Move regions

- [ ] Image processing (de/normalize, transform heights, resize maps, swap texture ids by changing the control map pixels)

- [ ] Restructure channel packer code to remove find_child
  
- [ ]  Region viewer (heightmap / normal / color / control thumbnail view of each region)

- [ ] An information panel (# regions, total space used, map resolution, texture resolution, memory used, texture resolution, filenames, etc) (shown: GTerrain, precursor to Terrain3D)

![image](https://github.com/TokisanGames/Terrain3D/assets/632766/34389008-37dd-4403-905a-05d07cffa767)

- [ ]  A terrain generator (shown: Zylann's HTerrain) #101 

![image](https://github.com/TokisanGames/Terrain3D/assets/632766/1ead3c18-7d82-4a9c-93fc-9da195c4f57e)

Finished:
- [x] Arraymesh baker
- [x] Occlusion Culling baker
- [x] [Navigation baker](https://github.com/TokisanGames/Terrain3D/pull/253)
- [X] Channel packer #125 
- [x] Channel packer improvements #308
- [x]  A comprehensive tools UI panel that houses all of these tools UIs. No separate dialog boxes. #697
